config/routes.rb
Rails.application.routes.draw do
  resources :terms, only: :show
  resources :officials, only: :show
  resources :divisions, only: :show
  resources :governments, only: :show

  get '/', to: 'pages#home'
end

app/models/address.rb
require 'forwardable'
require 'street_address'

class Address
  extend Forwardable

  attr_accessor :addy
  def_delegators :addy, :city, :state, :postal_code

  def initialize(text)
    @addy = StreetAddress::US.parse(text)
  end


  def house_number_and_street
    [addy.number, addy.street, addy.street_type].join(' ')
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/division.rb
class Division < ApplicationRecord
  self.primary_key = :slug
  has_many :terms, foreign_key: :division_slug
  has_many :officials, through: :terms

  scope :voting_precincts_with_centroids, -> () {
    select(*(Division.attribute_names + ['ST_ASGEOJSON(ST_CENTROID(geom)) AS centroid'])).
    where(
      government_slug: 'tx-county',
      category: 'Voting Precint'
    )
  }

  scope :for_point, -> (lat, lon) {
    where(
      "ST_Contains(divisions.geom, ST_Transform(ST_SetSRID(ST_MakePoint(?,?), 4326), 4326))",
      lon,
      lat
    )
  }

  def centroid
    @centroid ||= JSON.parse(attribute(:centroid))
  end

  def centroid_lat
    centroid['coordinates'].last
  end

  def centroid_lon
    centroid['coordinates'].first
  end
end

app/models/geocoder.rb
require 'smartystreets'

module Geocoder
  extend self

  def auth_id
    ENV.fetch('SMARTYSTREETS_AUTH_ID')
  end
  def auth_token
    ENV.fetch('SMARTYSTREETS_TOKEN')
  end

  def call(street:, city:, zipcode:)
    if auth_id == 'fake'
      Fake.call
    else
      Live.call street: street,
          city: city,
          zipcode: zipcode
    end
  end

  module Live
    def self.call(street:, city:, zipcode:)
      result = SmartyStreets::StreetAddressApi.call(
				SmartyStreets::StreetAddressRequest.new(
					input_id: "1",
					street: street,
					city: city,
					state: "TX",
					zipcode: zipcode
				)
			).first or raise "Failed getting smarty streets"
      { latitude: result.metadata.latitude, longitude: result.metadata.longitude }
    end
  end

  module Fake
    def self.call
      { latitude: 29.742722, longitude: -95.402197 }
    end
  end

end

app/models/government.rb
class Government < ApplicationRecord
  self.primary_key = :slug
  has_many :divisions, foreign_key: :government_slug
end

app/models/lookup_people_by_address.rb
class LookupPeopleByAddress

  def self.call(address_text)
    new(address_text).call
  end

  attr_accessor :address_text

  def initialize(address_text)
    @address_text = address_text
  end

  def call
    if address && location
      Government.joins(divisions: { terms: :official }).inject({}) do |hsh, government|
        #where('"terms"."start_date" < NOW() AND "terms"."end_date" > NOW()').
        hsh.merge(
          government => government.divisions.for_point(
            location[:latitude],
            location[:longitude]
          )
        )
      end
    else
      []
    end
  end

  def address
    @address ||= Address.new address_text
  end

  def location
    @location ||= Rails.cache.fetch(location_cache_key) {
      Geocoder.call(
        street: address.house_number_and_street,
        city: address.city,
        zipcode: address.postal_code
      )
    }
  end

  def location_cache_key
    [address.house_number_and_street, address.city, address.postal_code].compact.map do |s|
      s.downcase.strip.gsub(/\s+/, ' ')
    end.join(' ')
  end

end

app/models/official.rb
class Official < ApplicationRecord
  self.primary_key = :slug
  has_many :terms, foreign_key: :official_slug  # lol maybe not

  mount_uploader :photo, PhotoUploader
end

app/models/person.rb
class Person < ApplicationRecord
  self.primary_key = :slug
  has_many :terms, foreign_key: :person_slug  # lol maybe not
  has_many :governemnts, through: :terms

  mount_uploader :photo, PhotoUploader
end

app/models/term.rb
class Term < ApplicationRecord
  belongs_to :official, foreign_key: :official_slug, primary_key: :slug
  belongs_to :division, foreign_key: :division_slug, primary_key: :slug

  scope :current, -> { where('"terms"."start_date" < NOW() AND "terms"."end_date" > NOW()') }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController

  # GET /divisions/1
  def show
    @division = Division.
      select(*(Division.attribute_names + ['ST_ASGEOJSON(geom) AS geom_geojson'])).
      where(slug: params[:id]).
      first
  end

end

app/controllers/governments_controller.rb
class GovernmentsController < ApplicationController
  before_action :set_government, only: :show

  # GET /governments/1
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_government
      @government = Government.find_by(slug: params[:id])
    end
end

app/controllers/officials_controller.rb
class OfficialsController < ApplicationController
  before_action :set_official, only: :show

  # GET /officials/1
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_official
      @official = Official.find_by(slug: params[:id])
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if params[:location]
      @results = LookupPeopleByAddress.call params[:location]
    end
  end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  before_action :set_term, only: [:show, :edit, :update, :destroy]

  # GET /terms
  def index
    @terms = Term.all
  end

  # GET /terms/1
  def show
  end

  # GET /terms/new
  def new
    @term = Term.new
  end

  # GET /terms/1/edit
  def edit
  end

  # POST /terms
  def create
    @term = Term.new(term_params)

    if @term.save
      redirect_to @term, notice: 'Term was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /terms/1
  def update
    if @term.update(term_params)
      redirect_to @term, notice: 'Term was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /terms/1
  def destroy
    @term.destroy
    redirect_to terms_url, notice: 'Term was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_term
      @term = Term.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def term_params
      params.require(:term).permit(:government_slug, :person_slug, :name, :start_date, :end_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/governments_helper.rb
module GovernmentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/divisions/show.html.erb
<% content_for :head do %>
  <script src='https://api.mapbox.com/mapbox.js/v3.0.1/mapbox.js'></script>
  <link href='https://api.mapbox.com/mapbox.js/v3.0.1/mapbox.css' rel='stylesheet' />

  <style>
    #map { height: 280px; }
  </style>
<% end %>

<h2><%= @division.name %></h2>

<h3>Current <%= pluralize(@division.officials.length, 'officeholder') %></h3>

<div class="panel-body">
  <% @division.officials.each do |official| %>
    <%= render partial: 'official/official', object: official %>
  <% end %>
</div>

<div id="map"></div>


<script type="text/javascript">
  $(function() {
    L.mapbox.accessToken = '<%= ENV.fetch('MAPBOX_API_KEY') %>'
    var map = L.mapbox.map('map', 'mapbox.streets')

    var geo = L.geoJSON(<%= @division.geom_geojson.html_safe %>).addTo(map)
    map.fitBounds(geo.getBounds())
  })
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= yield :head %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Houvote", "#", class: "navbar-brand" %>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="/">Home</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/official/_official.html.erb
<div class="thumbnail">
  <img src="<%= official.third_party_photo_url %>">
  <div class="caption">
    <h4><%= link_to official.name, official %></h3>
  </div>
</div>

app/views/official/show.html.erb
<div class="page-header">
  <h1><%= @official.name %></h1>
</div>

<dl class="dl-horizontal">
  <dt>Slug:</dt>
  <dd><%= @official.slug %></dd>

  <dt>Photo:</dt>
  <dd><%= @official.photo %></dd>

  <dt>Born:</dt>
  <dd><%= @official.born %></dd>

</dl>

app/views/pages/home.html.erb
<form action="/" method="get">
  <div class="form-group">
    <label class: "col-sm-2 control-label" for="location">Location</label>
    <div class="col-sm-10">
      <input type="text" name="location" class="form-control" />
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <input type="submit" value="Submit" />
    </div>
  </div>
</form>

<% if @results %>
  <div class="list-group">
    <% @results.each do |government, divisions| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="panel-title"><%= government.name %></h3>
        </div>
        <div class="panel-body">
          <% divisions.each do |division| %>
            <h3><%= link_to division.name, division %></h3>
            <% division.terms.each do |term| %>
              <%= render partial: 'official/official', object: term.official %>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/terms/_form.html.erb
<%= simple_form_for(@term, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= f.label :government_slug, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.input :government_slug, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :person_slug, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.input :person_slug, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.input :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :start_date, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.input :start_date, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :end_date, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.input :end_date, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.button :submit, class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/terms/edit.html.erb
<div class="page-header">
  <%= link_to terms_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @term, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing term</h1>
</div>

<%= render 'form' %>

app/views/terms/index.html.erb
<div class="page-header">
  <%= link_to new_term_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Term
  <% end %>
  <h1>Listing terms</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Government slug</th>
            <th>Person slug</th>
            <th>Name</th>
            <th>Start date</th>
            <th>End date</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @terms) do |term| %>
            <td><%= term.government_slug %></td>
            <td><%= term.person_slug %></td>
            <td><%= term.name %></td>
            <td><%= term.start_date %></td>
            <td><%= term.end_date %></td>
            <td><%= link_to 'Show', term %></td>
        <td><%= link_to 'Edit', edit_term_path(term) %></td>
        <td><%= link_to 'Destroy', term, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/terms/new.html.erb
<div class="page-header">
  <%= link_to terms_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New term</h1>
</div>

<%= render 'form' %>

app/views/terms/show.html.erb
<div class="page-header">
  <%= link_to terms_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_term_path(@term), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show term</h1>
</div>

<dl class="dl-horizontal">
  <dt>Government slug:</dt>
  <dd><%= @term.government_slug %></dd>

  <dt>Person slug:</dt>
  <dd><%= @term.person_slug %></dd>

  <dt>Name:</dt>
  <dd><%= @term.name %></dd>

  <dt>Start date:</dt>
  <dd><%= @term.start_date %></dd>

  <dt>End date:</dt>
  <dd><%= @term.end_date %></dd>

</dl>